### ISSUE TITLE
APIError: {"message":"Forbidden"}

### ISSUE THREAD

**Issue by robmarkcole** [GEOSYS/earthdaily-python-client#10]
I've noticed that if the API hasn't been queried for a while this error is raised. Calling `earthdatastore.Auth()` refreshes the connection and clears the error. We could consider this automatically

**Comment by nkarasiak** [comment]
Yes there's an one hour timeout of the authentification. It could be nice to automatically reauth() when this error pop.

**Comment by nkarasiak** [comment]
A way to handle easilly the reauth (need to be implemented inside the package)
```
resp = eds.client._stac_io.session.get(eds.client.get_self_href())
if resp.status_code == 403:
    eds = earthdaily.earthdatastore.Auth()
```
