### ISSUE TITLE
Protect main branch

### ISSUE THREAD

**Issue by robmarkcole** [GEOSYS/earthdaily-python-client#13]
Its possible to protect the main branch and enforce PRs via dev branch - not sure this is available on current GH plan. Not an issue currently but if we plan for more contributors its a good idea

**Comment by nkarasiak** [comment]
This branch nows need a pull request, you cannot push anymore directly to `main` . So every code suggestion should be made if possible on `dev` or another specific branch.
But one thing to ensure a code reliability is to pull only if some github actions succeeded (like documentation, unit test...). When we will have unit tests it'll be the time to do it.
