### ISSUE TITLE
Enhancement for example venus_cube_mask.py

### ISSUE THREAD

**Issue by robmarkcole** [GEOSYS/earthdaily-python-client#6]
To make the plot display when run from the command line, it's necessary to include:

```
import matplotlib.pyplot as plt


# at end
plt.show()
```

**Comment by robmarkcole** [comment]
Also true for `venus_cube.py`

**Comment by nkarasiak** [comment]
Thanks !
I kept only this venus example in order to build the documentation fastly : https://geosys.github.io/earthdaily-python-client/_auto_examples/venus_cube_mask.html#sphx-glr-auto-examples-venus-cube-mask-py
