### ISSUE TITLE
Integrate demo geometry (pivot.geojson for example) inside code

### ISSUE THREAD

**Issue by nkarasiak** [GEOSYS/earthdaily-python-client#7]
For now the package has not geometry example in order to test and try directly a geometry. The geometry (pivot.geojson) is just a geojson file inside the examples folder, so not available when downloading the notebooks.
That can be very useful to have it inside the code ([see sklearn datasets](https://scikit-learn.org/stable/datasets.html))

**Comment by robmarkcole** [comment]
@nkarasiak based on previous experience, having the files in the repo is preferable to external download links which can break. However these should be kept lightweight

**Comment by nkarasiak** [comment]
Implemented in since v0.0.1-rc5 #17
